web/router.ex
defmodule Runeforge.Router do
  use Runeforge.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Runeforge.Auth, repo: Runeforge.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Runeforge do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/characters", CharacterController do
      get "/spawn", CharacterController, :spawn, as: :spawn
    end

    resources "/players", PlayerController do
      get "/join", PlayerController, :join, as: :join
      get "/leave", PlayerController, :leave, as: :leave
    end

    resources "/lobby", LobbyController
    post "/lobby/join", LobbyController, :join
  end

  # Other scopes may use custom stacks.
  # scope "/api", Runeforge do
  #   pipe_through :api
  # end
end

web/models/player.ex
defmodule Runeforge.Player do
  use Runeforge.Web, :model

  schema "players" do
    field :name, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
  end
end

web/controllers/player_controller.ex
defmodule Runeforge.PlayerController do
  use Runeforge.Web, :controller

  alias Runeforge.Player

  def index(conn, _params) do
    players = Repo.all(Player)
    render(conn, "index.html", players: players)
  end

  def new(conn, _params) do
    changeset = Player.changeset(%Player{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"player" => player_params}) do
    changeset = Player.changeset(%Player{}, player_params)

    case Repo.insert(changeset) do
      {:ok, _player} ->
        conn
        |> put_flash(:info, "Player created successfully.")
        |> redirect(to: player_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    player = Repo.get!(Player, id)
    render(conn, "show.html", player: player)
  end

  def edit(conn, %{"id" => id}) do
    player = Repo.get!(Player, id)
    changeset = Player.changeset(player)
    render(conn, "edit.html", player: player, changeset: changeset)
  end

  def update(conn, %{"id" => id, "player" => player_params}) do
    player = Repo.get!(Player, id)
    changeset = Player.changeset(player, player_params)

    case Repo.update(changeset) do
      {:ok, player} ->
        conn
        |> put_flash(:info, "Player updated successfully.")
        |> redirect(to: player_path(conn, :show, player))
      {:error, changeset} ->
        render(conn, "edit.html", player: player, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    player = Repo.get!(Player, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(player)

    conn
    |> put_flash(:info, "Player deleted successfully.")
    |> redirect(to: player_path(conn, :index))
  end

  def join(conn, %{"player_id" => id}) do
    player = Repo.get!(Player, id)

    :ok = Runeforge.PlayerServer.join(player)

    conn
    |> Runeforge.Auth.login(player)
    |> put_flash(:info, "#{player.name} has joined the session.")
    |> redirect(to: player_path(conn, :index))
  end

  def leave(conn, %{"player_id" => id}) do
    player = Repo.get!(Player, id)
    :ok = Runeforge.PlayerServer.leave(player)

    conn
    |> Runeforge.Auth.logout()
    |> put_flash(:info, "#{player.name} has left the session.")
    |> redirect(to: player_path(conn, :index))
  end
end

web/views/player_view.ex
defmodule Runeforge.PlayerView do
  use Runeforge.Web, :view
end

web/templates/player/edit.html.eex
<h2>Edit player</h2>

<%= render "form.html", changeset: @changeset,
                        action: player_path(@conn, :update, @player) %>

<%= link "Back", to: player_path(@conn, :index) %>

web/templates/player/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/player/index.html.eex
<h2>Listing players</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for player <- @players do %>
    <tr>
      <td><%= player.name %></td>

      <td class="text-right">
        <%= unless @current_player do %>
        <%= link "Join", to: player_join_path(@conn, :join, player.id), class: "btn btn-default btn-xs" %>
        <% end %>
        <%= link "Show", to: player_path(@conn, :show, player), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: player_path(@conn, :edit, player), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: player_path(@conn, :delete, player), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New player", to: player_path(@conn, :new) %>

web/templates/player/new.html.eex
<h2>New player</h2>

<%= render "form.html", changeset: @changeset,
                        action: player_path(@conn, :create) %>

<%= link "Back", to: player_path(@conn, :index) %>

web/templates/player/show.html.eex
<h2>Show player</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @player.name %>
  </li>

</ul>

<%= link "Edit", to: player_path(@conn, :edit, @player) %>
<%= link "Back", to: player_path(@conn, :index) %>