web/router.ex
defmodule Runeforge.Router do
  use Runeforge.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Runeforge.Auth, repo: Runeforge.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Runeforge do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/characters", CharacterController do
      get "/spawn", CharacterController, :spawn, as: :spawn
    end

    resources "/players", PlayerController do
      get "/join", PlayerController, :join, as: :join
      get "/leave", PlayerController, :leave, as: :leave
    end

    resources "/lobby", LobbyController
    post "/lobby/join", LobbyController, :join
  end

  # Other scopes may use custom stacks.
  # scope "/api", Runeforge do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Runeforge.LayoutView do
  use Runeforge.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Runeforge!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <!-- React libraries. -->
    <script src="https://unpkg.com/react@latest/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@latest/dist/react-dom.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">
      <!-- <header class="header"> -->
      <nav class="navbar navbar-default">

        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= page_path(@conn, :index) %>">Runeforge</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
              <li class="active">
                <a href="http://www.phoenixframework.org/docs">Get Started</a>
              </li>
              <%= if @current_player do %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= @current_player.name %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link "Home", to: player_path(@conn, :show, @current_player) %></li>
                  <li><%= link "Logout", to: player_leave_path(@conn, :leave, @current_player.id) %></li>
                </ul>
              </li>
              <% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      <!-- </header> -->

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </div>
    <div class="container-fluid">
      <div class="row">
        <!-- Sidebar -->
        <div  class="col-md-2">
          <ul class="list-group">
            <li  class="list-group-item"><%= link "Home", to: page_path(@conn, :index) %></li>
            <li  class="list-group-item"><%= link "Players", to: player_path(@conn, :index) %></li>
            <li  class="list-group-item"><%= link "Characters", to: character_path(@conn, :index) %></li>
          </ul>
        </div>

        <!-- Main Box -->
        <div  class="col-md-10">
          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>
        </div>
      </div>

    </div> <!-- /container -->
    <script>window.userToken = "<%= assigns[:player_token] %>"</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>