web/router.ex
defmodule Runeforge.Router do
  use Runeforge.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Runeforge.Auth, repo: Runeforge.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Runeforge do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/characters", CharacterController do
      get "/spawn", CharacterController, :spawn, as: :spawn
    end

    resources "/players", PlayerController do
      get "/join", PlayerController, :join, as: :join
      get "/leave", PlayerController, :leave, as: :leave
    end

    resources "/lobby", LobbyController
    post "/lobby/join", LobbyController, :join
  end

  # Other scopes may use custom stacks.
  # scope "/api", Runeforge do
  #   pipe_through :api
  # end
end

web/models/character.ex
# Created with command:
# ```
#   mix phoenix.gen.html Character characters name:string hp:integer bloodied:integer \
#     ac:integer fort:integer ref:integer will:integer str:integer con:integer \
#     dex:integer int:integer wis:integer cha:integer
# ```
# It additionally created:
#   * creating web/controllers/character_controller.ex
#   * creating web/templates/character/edit.html.eex
#   * creating web/templates/character/form.html.eex
#   * creating web/templates/character/index.html.eex
#   * creating web/templates/character/new.html.eex
#   * creating web/templates/character/show.html.eex
#   * creating web/views/character_view.ex
#   * creating test/controllers/character_controller_test.exs
#   * creating web/models/character.ex
#   * creating test/models/character_test.exs
#   * creating priv/repo/migrations/20161219034413_create_character.exs

defmodule Runeforge.Character do
  use Runeforge.Web, :model

  @derive {Poison.Encoder, only: [:name, :hp, :bloodied]}

  schema "characters" do
    field :name, :string
    field :hp, :integer
    field :bloodied, :integer

    field :ac, :integer
    field :fort, :integer
    field :ref, :integer
    field :will, :integer
    field :str, :integer
    field :con, :integer
    field :dex, :integer
    field :int, :integer
    field :wis, :integer
    field :cha, :integer

    field :owner, :integer

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :hp, :bloodied, :ac, :fort, :ref, :will, :str, :con, :dex, :int, :wis, :cha, :owner])
    |> validate_required([:name, :hp, :bloodied, :ac, :fort, :ref, :will, :str, :con, :dex, :int, :wis, :cha])
  end

  def get_by_owner(owner_id) do
    query = from c in Runeforge.Character,
          where: c.owner == ^owner_id,
          select: c

    Runeforge.Repo.all(query)
  end
end

web/controllers/character_controller.ex
defmodule Runeforge.CharacterController do
  require Logger

  use Runeforge.Web, :controller

  alias Runeforge.Character

  def index(conn, _params) do
    owned_list = []
    player = nil

    if @current_player do
      player = @current_player
      player_id = @current_player.id

      {:ok, owned_list} = Runeforge.BoardServer.get_owned(player.id)
      owned_list = Enum.reduce(owned_list, [],
        fn({_, %{character: %{id: id}}}, acc) -> [id | acc]
          (_, acc) -> acc
        end
      )
    end

    IO.inspect "---------------------"
    IO.inspect owned_list

    characters = Repo.all(Character)
    |> Enum.reduce({[], []},
      fn(char, {owned, available}) ->
        case Enum.member?(owned_list, char.id) do
          true -> {[char | owned], available}
          _ -> {owned, [char | available]}
        end
      end
    )
    render(conn, "index.html", characters: %{}, player: player)
  end

  def new(conn, _params) do
    changeset = Character.changeset(%Character{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"character" => character_params}) do
    # player = get_session(conn, :player)
    # character_params = %{character_params | :owner}
    # changeset = Character.changeset(%Character{}, character_params)
    #
    # case Repo.insert(changeset) do
    #   {:ok, _character} ->
    #     conn
    #     |> put_flash(:info, "Character created successfully.")
    #     |> redirect(to: character_path(conn, :index))
    #   {:error, changeset} ->
    #     render(conn, "new.html", changeset: changeset)
    # end
  end

  def show(conn, %{"id" => id}) do
    character = Repo.get!(Character, id)
    render(conn, "show.html", character: character)
  end

  def edit(conn, %{"id" => id}) do
    character = Repo.get!(Character, id)
    changeset = Character.changeset(character)
    render(conn, "edit.html", character: character, changeset: changeset)
  end

  def update(conn, %{"id" => id, "character" => character_params}) do
    character = Repo.get!(Character, id)
    changeset = Character.changeset(character, character_params)

    case Repo.update(changeset) do
      {:ok, character} ->
        conn
        |> put_flash(:info, "Character updated successfully.")
        |> redirect(to: character_path(conn, :show, character))
      {:error, changeset} ->
        render(conn, "edit.html", character: character, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    character = Repo.get!(Character, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(character)

    conn
    |> put_flash(:info, "Character deleted successfully.")
    |> redirect(to: character_path(conn, :index))
  end

  def spawn(conn, %{"character_id" => character_id}) do
    player = get_session(conn, :player)
    Runeforge.BoardServer.spawn(character_id, player.id)

    conn
    |> put_flash(:info, "Character spawned.")
    |> redirect(to: character_path(conn, :index))
  end
end

web/views/character_view.ex
defmodule Runeforge.CharacterView do
  use Runeforge.Web, :view
end

web/templates/character/edit.html.eex
<h2>Edit character</h2>

<%= render "form.html", changeset: @changeset,
                        action: character_path(@conn, :update, @character) %>

<%= link "Back", to: character_path(@conn, :index) %>

web/templates/character/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :hp, class: "control-label" %>
    <%= number_input f, :hp, class: "form-control" %>
    <%= error_tag f, :hp %>
  </div>

  <div class="form-group">
    <%= label f, :bloodied, class: "control-label" %>
    <%= number_input f, :bloodied, class: "form-control" %>
    <%= error_tag f, :bloodied %>
  </div>

  <div class="form-group">
    <%= label f, :ac, class: "control-label" %>
    <%= number_input f, :ac, class: "form-control" %>
    <%= error_tag f, :ac %>
  </div>

  <div class="form-group">
    <%= label f, :fort, class: "control-label" %>
    <%= number_input f, :fort, class: "form-control" %>
    <%= error_tag f, :fort %>
  </div>

  <div class="form-group">
    <%= label f, :ref, class: "control-label" %>
    <%= number_input f, :ref, class: "form-control" %>
    <%= error_tag f, :ref %>
  </div>

  <div class="form-group">
    <%= label f, :will, class: "control-label" %>
    <%= number_input f, :will, class: "form-control" %>
    <%= error_tag f, :will %>
  </div>

  <div class="form-group">
    <%= label f, :str, class: "control-label" %>
    <%= number_input f, :str, class: "form-control" %>
    <%= error_tag f, :str %>
  </div>

  <div class="form-group">
    <%= label f, :con, class: "control-label" %>
    <%= number_input f, :con, class: "form-control" %>
    <%= error_tag f, :con %>
  </div>

  <div class="form-group">
    <%= label f, :dex, class: "control-label" %>
    <%= number_input f, :dex, class: "form-control" %>
    <%= error_tag f, :dex %>
  </div>

  <div class="form-group">
    <%= label f, :int, class: "control-label" %>
    <%= number_input f, :int, class: "form-control" %>
    <%= error_tag f, :int %>
  </div>

  <div class="form-group">
    <%= label f, :wis, class: "control-label" %>
    <%= number_input f, :wis, class: "form-control" %>
    <%= error_tag f, :wis %>
  </div>

  <div class="form-group">
    <%= label f, :cha, class: "control-label" %>
    <%= number_input f, :cha, class: "form-control" %>
    <%= error_tag f, :cha %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/character/index.html.eex
<% {owned, available} = @characters %>
<%= if @current_player do %>
  <h2><%= @current_player.name %></h2>
  <%= link "Leave", to: player_leave_path(@conn, :leave, @current_player.id) %>

  <h3>Owned</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Hp</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
  <%= for character <- owned do %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.hp %></td>

        <td class="text-right">
          <%= if @current_player do %>
          <%= link "Despawn", to: character_spawn_path(@conn, :spawn, character.id), class: "btn btn-default btn-xs" %>
          <% end %>
          <%= link "Show", to: character_path(@conn, :show, character), class: "btn btn-default btn-xs" %>
          <%= link "Edit", to: character_path(@conn, :edit, character), class: "btn btn-default btn-xs" %>
          <%= link "Delete", to: character_path(@conn, :delete, character), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
  <hr />
<% end %>


<h2>Listing characters</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hp</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for character <- available do %>
    <tr>
      <td><%= character.name %></td>
      <td><%= character.hp %></td>

      <td class="text-right">
        <%= if @current_player do %>
        <%= link "Spawn", to: character_spawn_path(@conn, :spawn, character.id), class: "btn btn-default btn-xs" %>
        <% end %>
        <%= link "Show", to: character_path(@conn, :show, character), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: character_path(@conn, :edit, character), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: character_path(@conn, :delete, character), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New character", to: character_path(@conn, :new) %>